accounts/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
]

cart/urls.py
from django.urls import re_path

from . import views

app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.CartDetailView.as_view(), name='cart_detail'),
    re_path(r'^add/(?P<slug>[\w-]+)/$', views.CartAddView.as_view(), name='cart_add'),
    re_path(r'^remove/(?P<slug>[\w-]+)/$', views.CartRemoveView.as_view(), name='cart_remove'),
]

shop/urls.py
from django.urls import re_path

from . import views
from .views import OrderCheckoutView

app_name = 'shop'

urlpatterns = [
    re_path(r'^$', views.ProductsListView.as_view(), name='products'),
    re_path(r'^checkout/$', OrderCheckoutView.as_view(), name='checkout'),
    re_path(r'^product/(?P<slug>[\w-]+)/$', views.ProductView.as_view(), name='product'),
    re_path(r'^order_create/$', views.OrderCreateApiView.as_view(), name='order_create'),
    re_path(r'^verify/', views.OrderVerifyApiView.as_view(), name='verify'),
    re_path(r'^categpry/(?P<slug>[\w\-]+)/posts/$', views.ProductCategoryPostsView.as_view(), name='category_posts'),
]

shop/models.py
from .submodels.product import Product
from .submodels.product import ProductTag
from .submodels.product import ProductStatus
from .submodels.product import ProductReview
from .submodels.product import ProductPicture
from .submodels.product import ProductMovie
from .submodels.product import ProductLevel
from .submodels.product import ProductCategory
from .submodels.product import ProductBadge

from .submodels.order import Order
from .submodels.order_item import OrderItem

shop/views.py
from shop.subviews.product import ProductsListView
from shop.subviews.product import ProductView
from shop.subviews.product import ProductViewSet

from shop.subviews.order import OrderCheckoutApiView
from shop.subviews.order import OrderVerifyApiView
from shop.subviews.order import OrderViewSet
from shop.subviews.order import OrderCreateApiView
from shop.subviews.order import OrderCheckoutView
from shop.subviews.product import ProductCategoryPostsView
from shop.subviews.order_items import OrderItemsViewSet

media/templates/pages/shop/checkout.html
{% extends 'shared/_site.html' %}
{% load static %}

{% block body %}

    <div class="bradcam_area breadcam_bg_3">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <!-- <h3>Contact Us</h3> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="contact-section section_padding">
        <div class="container">
            <div class="wrap cf">
                <h1 class="projTitle"> لیست خرید محصول های آموزشی </h1>
                <div class="heading cf">
                    <h1>لیست خرید </h1>
                    <a href="{% url 'shop:products' %}" class="continue">ادامه خرید </a>
                </div>
                <div class="cart">
                    <ul class="cartWrap">
                        {% for item in cart %}
                            {% with product=item.product %}
                                <li class="items odd">

                                    <div class="infoWrap">
                                        <div class="cartSection">
                                            <img src="http://lorempixel.com/output/technics-q-c-300-300-4.jpg" alt=""
                                                 class="itemImg"/>
                                            <p class="itemNumber">{{ product.slug }}</p>
                                            <h3>{{ product.titleo }}</h3>

                                            <p><input type="text" class="qty"
                                                      placeholder="{{ item.quantity }}"/>{{ product.price }}$</p>
                                            {% if product.available %}
                                                <p class="stockStatus"> موجود</p>
                                            {% else %}
                                                <p class="stockStatus">ناموجود</p>
                                            {% endif %}
                                        </div>


                                        <div class="prodTotal cartSection">
                                            <p>{{ item.total_price }}</p>
                                        </div>
                                        <div class="cartSection removeWrap">
                                            <a href="{% url 'cart:cart_remove' product.slug %}" class="remove">x</a>
                                        </div>
                                    </div>
                                </li>
                            {% endwith %}
                        {% endfor %}



                        <!--<li class="items even">Item 2</li>-->

                    </ul>
                </div>

                <div class="promoCode"><label for="promo">کد تخفیف دارید؟</label><input type="text" name="promo"
                                                                                        placholder="Enter Code"/>
                    <a href="#" class="btn"></a></div>

                <div class="subtotal cf">
                    <ul>
                        <li class="totalRow"><span class="label">موضوع</span><span
                                class="value">{{ cart.get_total_price }}</span></li>

                        <li class="totalRow"><span class="label">پرداختی</span><span
                                class="value">{{ cart.get_total_price }}</span></li>

                        <li class="totalRow"><span class="label">مالیات</span><span class="value">$4.00</span></li>
                        <li class="totalRow final"><span class="label">جمع کل</span><span
                                class="value">{{ cart.get_total_price }}</span>
                        </li>

                        <li class="totalRow">
                            {% if user.is_authenticated %}
                                <a class="btn icon-left float-right mt-3" href="{% url 'shop:order_create' %}"><span>پرداخت</span></a>
                            {% else %}
                                <a class="btn icon-left float-right mt-3" href="{% url 'accounts:register' %}"><span>ورود به سایت </span></a>

                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

media/templates/pages/shop/product.html
{% extends 'shared/_site.html' %}
{% load static %}

{% block body %}

    <div class="bradcam_area breadcam_bg_3">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <!-- <h3>Contact Us</h3> -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="contact-section section_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="single-shop">
                        <div><h4>جزئیات محصول</h4></div>
                        <hr/>
                        <div class="row">
                            <div class="col-md-9">
                                <div class="row product-summary my-3">
                                    <div class="col-md-3"><img class="product-image" alt="numbr" src="


                                            {% for pic in product.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %}"/>
                                    </div>
                                    <div class="col-md-9">
                                        <h4>{{ product.title }}</h4>

                                        <hr/>
                                        {{ product.content|safe }}
                                    </div>

                                </div>
                                <hr/>
                                <div class="row">
                                    <form action="{% url 'cart:cart_add' product.slug %}" method="post">
                                        <div class="col-md-6">
                                            {% csrf_token %}
                                            {{ cart_add_product_form }}
                                            <button class="btn btn-danger m-4 px-5 py-2"
                                                    style="font-family: 'ravi-thin';">خرید
                                            </button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="cost-summary my-3">
                                    <div>
                                        <p>قیمت کالا</p>
                                        <p class="float-left"> ریال </p>
                                        <p class="float-left"> {{ product.price }} </p>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

media/templates/pages/shop/products.html
{% extends 'shared/_site.html' %}
{% load static %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area breadcam_bg_3">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="contact-section section_padding">
        <div class="container">
            <div class="row">
                {% include 'partials/aside.html' %}
                <div class="col-md-8">
                    <div class="products">
                        {% for product in products %}
                            <div class="col-sm-3 blog-shop">
                                <div class="col-item">
                                    <div class="photo">
                                        <img src=
                                                     {% for pic in product.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %} class="img-responsive"
                                             alt="a"/>
                                    </div>
                                    <div class="info">
                                        <div class="row">
                                            <div class="price col-md-12">
                                                <h5>
                                                    <a href="{{ product.get_absolute_url }}">
                                                        {{ product.title }}
                                                    </a>
                                                </h5>
                                            </div>
                                            <div class="rating hidden-sm col-md-12">
                                                <h5 class="price-text-color">{{ product.price }}</h5>
                                            </div>
                                        </div>
                                        <form action="{% url 'shop:product' product.slug %}">
                                            <div class="separator clear-left">
                                                <button class="btn-add button button-contactForm btn_4 boxed-btn">
                                                    اضافه کردن
                                                    <i class="fa fa-shopping-cart"></i>
                                                </button>
                                            </div>
                                        </form>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}