analysis/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'technofund'
urlpatterns = [
    re_path(r'^$', views.AnalyzeView.as_view(), name='posts'),
    re_path(r'^categpry/(?P<slug>[\w\-]+)/posts/$', views.TechnofundCategoryPostsView.as_view(), name='category_posts'),
    re_path(r'^search/$', views.TechnofundSearchPostView.as_view(), name='search_posts'),
    re_path(r'^(?P<slug>[\w\-]+)/$', views.SingleAnalyzeView.as_view(), name='post'),
]

api/v1/news/urls.py
from rest_framework import routers
from django.urls import re_path

from . import views as view

router = routers.SimpleRouter()

router.register(r'news/category', view.NewsCategoryViewSet)
router.register(r'news', view.NewsPostViewSet)
# router.register(r'analysis', view.AnalyzePostViewSet)

urlpatterns = router.urls

cart/urls.py
from django.urls import re_path

from . import views

app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.CartDetailView.as_view(), name='cart_detail'),
    re_path(r'^add/(?P<slug>[\w-]+)/$', views.CartAddView.as_view(), name='cart_add'),
    re_path(r'^remove/(?P<slug>[\w-]+)/$', views.CartRemoveView.as_view(), name='cart_remove'),
]

news/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'news'
urlpatterns = [
    re_path(r'^$', views.NewsListView.as_view(), name='posts'),
    re_path(r'^category/(?P<slug>[\w\-]+)/posts/$', views.NewsCategoryPostsView.as_view(), name='category_posts'),
    re_path(r'^search/$', views.NewsSearchPostView.as_view(), name='search_posts'),
    re_path(r'^(?P<slug>[\w\-]+)/$', views.SinglePostNewsDetail.as_view(), name='post'),
]

news/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField

class NewsPost(models.Model):
    title = models.CharField(_("Title"), max_length=120)
    slug = models.SlugField(_("Slug"), max_length=140, allow_unicode=True, editable = False)
    summary = RichTextField(max_length=400)

    content = RichTextUploadingField(_("Content"))

    source = models.URLField(_("Web Link Source"), max_length=200, null = True, blank = True)
    
    important = models.BooleanField(_("Important news"), default = False)
    is_shown = models.BooleanField(_("Show this news"), default = False)

    height_field = models.SmallIntegerField(_("Height Field"), editable = False)
    width_field = models.SmallIntegerField(_("Width Field"), editable = False)
    picture = models.ImageField(_("Picture"), upload_to='site/blog', height_field='height_field', width_field='width_field', max_length=254, help_text = _('picture size must be: 525x350'))
    alternate_picture = models.CharField(_("Alternate Picture"), max_length=120, help_text = _("use for SEO of picture"))

    author = models.ForeignKey(User, verbose_name=_("Author"), related_name = 'news_posts', on_delete=models.PROTECT)
    category = models.ForeignKey('NewsCategory', verbose_name=_("News Category"), related_name = 'posts', on_delete=models.PROTECT)
    tags = models.ManyToManyField('NewsTag', verbose_name=_("News Tags"))

    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)

    class Meta:
        verbose_name = _('News Post')
        verbose_name_plural = _('News Posts')
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)

        super(NewsPost, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('news:post', kwargs={'slug': self.slug})


class NewsCategory(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(_("Slug"), max_length=140)

    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)

    class Meta:
        verbose_name = _('News Category')
        verbose_name_plural = _('News Categories')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(NewsCategory, self).save(*args, **kwargs)
    
    def count_posts(self):
        return self.posts.count()
    
    def get_absolute_url(self):
        return reverse('news:category_posts', kwargs={'slug': self.slug})

class NewsTag(models.Model):

    title = models.CharField(max_length=120)
    slug = models.SlugField(_("Slug"), max_length=140)

    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)

    class Meta:
        verbose_name = _('News Tag')
        verbose_name_plural = _('News Tags')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(NewsTag, self).save(*args, **kwargs)

class NewsComment(models.Model):
    text = models.CharField(max_length=254)
    post = models.ForeignKey(NewsPost, verbose_name=_("NewsPost"), related_name = 'news_comments', on_delete=models.CASCADE)
    by = models.ForeignKey(User, verbose_name=_("By user"), related_name = 'news_comments', on_delete=models.PROTECT)
    reply = models.ForeignKey('NewsComment', verbose_name=_("reply"), related_name = 'news_comment', on_delete=models.SET_NULL, null = True, blank = True)

    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)

    class Meta:
        verbose_name = _('News Comment')
        verbose_name_plural = _('News Comments')

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
       super(NewsComment, self).save(*args, **kwargs)

api/v1/news/views.py
from .subviews.category import NewsCategoryViewSet
from .subviews.analyze import NewsPostViewSet

news/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import View
from django.utils.translation import ugettext_lazy as _

from .models import NewsCategory
from .models import NewsPost
from .models import NewsTag

from django.contrib.postgres.search import SearchVector
from django.urls import reverse_lazy
from django.shortcuts import redirect

class NewsListView(ListView):
    model = NewsPost
    context_object_name = 'posts'
    template_name = 'pages/news/posts.html'
    page_name = _('اخبار')

    def get_context_data(self, **kwargs):
        context = super(NewsListView, self).get_context_data(**kwargs)
        
        context['posts'] = NewsPost.objects.filter(important = True)
        context['recent_posts'] = NewsPost.objects.filter(important = True).order_by('-created')[:5]
        context['tags'] = NewsTag.objects.all()
        context['categories'] = NewsCategory.objects.all()

        return context

class NewsSearchPostView(View):
    template_name = 'pages/news/posts.html'
    context = dict()
    page_name = 'اخبار'

    def get(self, request, *args, **kwargs):
        return redirect(reverse_lazy('news:posts'))

    def post(self, request, *args, **kwargs):
        query = self.request.POST.get('search_content')
        vector = SearchVector('content', 'title')
        self.context['view'] = { 'page_name': self.page_name }
        self.context['tags'] = NewsPost.objects.all()
        self.context['categories'] = NewsCategory.objects.all()
        self.context['recent_posts'] = NewsPost.objects.filter(important = True).order_by('-created')[:5]
        self.context['posts'] = NewsPost.objects.annotate(search = vector).filter(search__icontains = query)
        return render(request, self.template_name, self.context)

class NewsCategoryPostsView(DetailView):
    model = NewsCategory
    template_name = 'pages/news/category.html'
    page_name = _('اخبار')
    slug_field = 'slug'
    context_object_name  = 'category'

    def get_context_data(self, **kwargs):
        context = super(NewsCategoryPostsView, self).get_context_data(**kwargs)
        context['categories'] = NewsCategory.objects.all()
        context['recent_posts'] = NewsPost.objects.order_by('-created')[:5]
        return context

class SinglePostNewsDetail(DetailView):
    model = NewsPost
    template_name = 'pages/news/post.html'
    context_object_name = 'post'
    page_name = _('اخبار')

    def get_context_data(self, **kwargs):
        context = super(SinglePostNewsDetail, self).get_context_data(**kwargs)
        context['posts'] = NewsPost.objects.all()
        context['recent_posts'] = NewsPost.objects.order_by('-created')[:5]
        context['tags'] = NewsTag.objects.all()
        context['categories'] = NewsCategory.objects.all()
        return context

media/templates/pages/news/category.html
{% extends 'shared/_site.html' %}
{% load static %}

{% block body %}
<div class="bradcam_area breadcam_bg_3">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3></h3>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget search_widget">
                        <form method="POST" action="{% url 'technofund:search_posts' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" name="search_content" placeholder='بنویس ، تا کمکت کنم..' />
                                    <div class="input-group-append">
                                        <button class="btn" type="button"><i class="ti-search"></i></button>
                                    </div>
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">جستجو</button>
                        </form>
                    </aside>
            
                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">دسته بندی</h4>
                        <ul class="list cat-list">
                            {% for category in categories %}
                                <li>
                                    <a href="{{ category.get_absolute_url }}" class="d-flex">
                                        <p style="margin-left: 5px;">{{ category.title }}</p>
                                        <p>( {{ category.count_posts }} )</p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </aside>
            
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">پست های اخیر و مهم</h3>
                        {% for post in recent_posts %}
                            <div class="media post_item">
                                {% if post.pictures %}
                                    <a href="{{ post.get_absolute_url }}">
                                        <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{% for pic in post.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %}" alt="" />
                                    </a>
                                {% else %}
                                    <a href="{{ post.get_absolute_url }}">
                                        <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{{ post.pictures.url }}" alt="" />
                                    </a>
                                {% endif %}
            
                                <div class="media-body" style="margin-right: 10px;">
                                    <a href="{{ post.get_absolute_url }}">
                                        <h3>{{ post.title }}</h3>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </aside>
                </div>
            </div>
            {% for post in category.posts.all %}
                <div class="col-lg-4" style="float:right;">
                    <div class="blog_left_sidebar">
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <a href="{{ post.get_absolute_url }}">
                                    <img  class="img-fluid card-img rounded-0" src="{{ post.picture.url }}" alt="" />
                                </a>
                            </div>

                            <div class="blog_details">
                                <a href="{{ post.get_absolute_url }}" class="d-inline-block">
                                    <h2>{{ post.title }}</h2>
                                </a>
                                <p>{{ post.summary }}</p>
                                <ul class="blog-info-a">
                                    <li><a href="{{ post.get_absolute_url }}"><i class="fa fa-angle-left"></i> بیشتر بدانید ...</a></li>
                                </ul>
                            </div>
                        </article>
                        </a>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
</section>
{% endblock %}

media/templates/pages/news/post.html
{% extends 'shared/_site.html' %}
{% load static %}

{% block body %}
<div class="bradcam_area breadcam_bg_3">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3></h3>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget search_widget">
                        <form method="POST" action="{% url 'news:search_posts' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" name="search_content" placeholder='بنویس ، تا کمکت کنم..' />
                                    <div class="input-group-append">
                                        <button class="btn" type="button"><i class="ti-search"></i></button>
                                    </div>
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">جستجو</button>
                        </form>
                    </aside>
            
                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">دسته بندی</h4>
                        <ul class="list cat-list">
                            {% for category in categories %}
                                <li>
                                    <a href="{{ category.get_absolute_url }}" class="d-flex">
                                        <p style="margin-left: 5px;">{{ category.title }}</p>
                                        <p>( {{ category.count_posts }} )</p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </aside>
            
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">پست های اخیر و مهم</h3>
                        {% for post in recent_posts %}
                            <div class="media post_item">
                                {% if post.pictures %}
                                    <a href="{{ post.get_absolute_url }}">
                                        <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{% for pic in post.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %}" alt="" />
                                    </a>
                                {% else %}
                                    <a href="{{ post.get_absolute_url }}">
                                        <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{{ post.pictures.url }}" alt="" />
                                    </a>
                                {% endif %}
            
                                <div class="media-body" style="margin-right: 10px;">
                                    <a href="{{ post.get_absolute_url }}">
                                        <h3>{{ post.title }}</h3>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </aside>
                </div>
            </div>
            
            <div class="col-lg-8 posts-list">
                <div class="single-post">
                    <div class="feature-img">
                        {% if post.pictures %}
                            <img  class="img-fluid card-img rounded-0" src="{% for pic in post.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %}" alt="" />
                        {% else %}
                            <img  class="img-fluid card-img rounded-0" src="{{ post.picture.url }}" alt="" />
                        {% endif %}
                    </div>
                    <br />
                    <div class="ck_beautify">
                        <h2>
                            {{ post.title }}
                        </h2>
                        {{ post.content|safe }}

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

media/templates/pages/news/posts.html
{% extends 'shared/_site.html' %}
{% load static %}

{% block body %}
<div class="bradcam_area breadcam_bg_3">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3></h3>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget search_widget">
                        <form method="POST" action="{% url 'news:search_posts' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" name="search_content" placeholder='بنویس ، تا کمکت کنم..' />
                                    <div class="input-group-append">
                                        <button class="btn" type="button"><i class="ti-search"></i></button>
                                    </div>
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">جستجو</button>
                        </form>
                    </aside>
            
                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">دسته بندی</h4>
                        <ul class="list cat-list">
                            {% for category in categories %}
                                <li>
                                    <a href="{{ category.get_absolute_url }}" class="d-flex">
                                        <p style="margin-left: 5px;">{{ category.title }}</p>
                                        <p>( {{ category.count_posts }} )</p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </aside>
            
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">پست های اخیر و مهم</h3>
                        {% for post in recent_posts %}
                            <div class="media post_item">
                                {% if post.pictures %}
                                    <a href="{{ post.get_absolute_url }}">
                                        <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{% for pic in post.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %}" alt="" />
                                    </a>
                                {% else %}
                                    <a href="{{ post.get_absolute_url }}">
                                        <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{{ post.pictures.url }}" alt="" />
                                    </a>
                                {% endif %}
            
                                <div class="media-body" style="margin-right: 10px;">
                                    <a href="{{ post.get_absolute_url }}">
                                        <h3>{{ post.title }}</h3>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </aside>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="row">
                    {% for post in posts %}
                        <div class="col-lg-6">
                            <div class="blog_left_sidebar">
                                <article class="blog_item">
                                    <div class="blog_item_img">
                                        {% if post.pictures %}
                                            <a href="{{ post.get_absolute_url }}">
                                                <img  class="img-fluid card-img rounded-0" src="{% for pic in post.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %}" alt="" />
                                            </a>
                                        {% else %}
                                            <a href="{{ post.get_absolute_url }}">
                                                <img  class="img-fluid card-img rounded-0" src="{{ post.picture.url }}" alt="" />
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div class="blog_details">
                                        <a href="{{ post.get_absolute_url }}" class="d-inline-block">
                                            <h2>{{ post.title }}</h2>
                                        </a>
                                        <p>{{ post.summary|safe }}</p>
                                        <ul class="blog-info-a">
                                            <li><a href="{{ post.get_absolute_url }}"> بیشتر بدانید ... <i class="fa fa-angle-left"></i></a></li>
                                        </ul>
                                    </div>
                                </article>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                </div>
                </div>

        </div>
    </div>
</section>
{% endblock %}