analysis/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'technofund'
urlpatterns = [
    re_path(r'^$', views.AnalyzeView.as_view(), name='posts'),
    re_path(r'^categpry/(?P<slug>[\w\-]+)/posts/$', views.TechnofundCategoryPostsView.as_view(), name='category_posts'),
    re_path(r'^search/$', views.TechnofundSearchPostView.as_view(), name='search_posts'),
    re_path(r'^(?P<slug>[\w\-]+)/$', views.SingleAnalyzeView.as_view(), name='post'),
]

cart/urls.py
from django.urls import re_path

from . import views

app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.CartDetailView.as_view(), name='cart_detail'),
    re_path(r'^add/(?P<slug>[\w-]+)/$', views.CartAddView.as_view(), name='cart_add'),
    re_path(r'^remove/(?P<slug>[\w-]+)/$', views.CartRemoveView.as_view(), name='cart_remove'),
]

news/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'news'
urlpatterns = [
    re_path(r'^$', views.NewsListView.as_view(), name='posts'),
    re_path(r'^category/(?P<slug>[\w\-]+)/posts/$', views.NewsCategoryPostsView.as_view(), name='category_posts'),
    re_path(r'^search/$', views.NewsSearchPostView.as_view(), name='search_posts'),
    re_path(r'^(?P<slug>[\w\-]+)/$', views.SinglePostNewsDetail.as_view(), name='post'),
]

pages/urls.py
from django.urls import path, re_path, include
from . import views


app_name = 'pages'
urlpatterns = [
    re_path(r'^$', views.HomeView.as_view(), name='home'),
    re_path(r'^contact/$', views.ContactView.as_view(), name='contact'),
    re_path(r'^about/$', views.AboutView.as_view(), name='about'),
    re_path(r'^open-account/$', views.OpenAccountView.as_view(), name='open-account'),
    re_path(r'^success/$', views.SuccessView.as_view(), name='success'),
]

shop/urls.py
from django.urls import re_path

from . import views
from .views import OrderCheckoutView

app_name = 'shop'

urlpatterns = [
    re_path(r'^$', views.ProductsListView.as_view(), name='products'),
    re_path(r'^checkout/$', OrderCheckoutView.as_view(), name='checkout'),
    re_path(r'^product/(?P<slug>[\w-]+)/$', views.ProductView.as_view(), name='product'),
    re_path(r'^order_create/$', views.OrderCreateApiView.as_view(), name='order_create'),
    re_path(r'^verify/', views.OrderVerifyApiView.as_view(), name='verify'),
    re_path(r'^categpry/(?P<slug>[\w\-]+)/posts/$', views.ProductCategoryPostsView.as_view(), name='category_posts'),
]

media/templates/partials/aside.html
<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <form method="POST" action="{% url 'technofund:search_posts' %}">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="search_content" placeholder='بنویس ، تا کمکت کنم..' />
                        <div class="input-group-append">
                            <button class="btn" type="button"><i class="ti-search"></i></button>
                        </div>
                    </div>
                </div>
                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                    type="submit">جستجو</button>
            </form>
        </aside>

        <aside class="single_sidebar_widget post_category_widget">
            <h4 class="widget_title">دسته بندی</h4>
            <ul class="list cat-list">
                {% for category in categories %}
                    <li>
                        <a href="{{ category.get_absolute_url }}" class="d-flex">
                            <p style="margin-left: 5px;">{{ category.title }}</p>
                            <p>( {{ category.count_posts }} )</p>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </aside>

        <aside class="single_sidebar_widget popular_post_widget">
            <h3 class="widget_title">پست های اخیر و مهم</h3>
            {% for post in recent_posts %}
                <div class="media post_item">
                    {% if post.pictures %}
                        <a href="{{ post.get_absolute_url }}">
                            <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{% for pic in post.pictures.all %}{% if forloop.first %} {{ pic.picture.url }} {% endif %}{% endfor %}" alt="" />
                        </a>
                    {% else %}
                        <a href="{{ post.get_absolute_url }}">
                            <img style="width:50px; height: 50px;"  class="img-fluid card-img rounded-0" src="{{ post.pictures.url }}" alt="" />
                        </a>
                    {% endif %}

                    <div class="media-body" style="margin-right: 10px;">
                        <a href="{{ post.get_absolute_url }}">
                            <h3 style="color: #727272">{{ post.title }}</h3>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </aside>
    </div>
</div>

media/templates/partials/footer.html
{% load static %}


<!-- footer start -->
<footer class="footer">
    <div class="footer_top">
        <div class="container-fluid p-0">
            <div class="row align-items-center no-gutters">
                <div class="col-lg-1 col-md-1">
                    <div class="footer_logo wow fadeInRight" data-wow-duration="1s" data-wow-delay=".3s">
                        <a href="/">
                            <img src="{% static 'assets/img/header/LOGO.png' %}" alt=""></img>
                        </a>
                    </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-9">
                    <div class="menu_links">                         
                        <ul>
                            <li class="{% if view.page_name == 'خانه' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".2s"><a href="{% url 'pages:home' %}">خانه</a></li>
                            <li class="{% if view.page_name == 'تکنوفاند' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".3s"><a href="{% url 'technofund:posts' %}">تکنوفاند </a></li>
                            <li class="{% if view.page_name == 'آموزش' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".4s"><a href="{% url 'tutorial:posts' %}"> آموزش </a></li>
                            <li class="{% if view.page_name == 'عرضه اولیه' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".5s"><a href="{% url 'market:primary-market' %}">عرضه اولیه</a></li>
                            <li class="{% if view.page_name == 'آکادمی' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".6s"><a href="{% url 'shop:products' %}">آکادمی</a></li>
                            <li class="{% if view.page_name == 'اخبار' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".7s"><a href="{% url 'news:posts' %}">اخبار</a></li>
                            <li class="{% if view.page_name == 'تماس با ما' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".8s"><a href="{% url 'pages:contact' %}">تماس با ما</a></li>
                            <li class="{% if view.page_name == 'درباره با ما' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay=".9s"><a href="{% url 'pages:about' %}">درباره با ما</a></li>
                            <li class="{% if view.page_name == 'افتتاح حساب آنلاین' %}say_hi {% endif %} wow fadeInDown" data-wow-duration="1s" data-wow-delay="1s"><a href="{% url 'pages:open-account' %}">افتتاح حساب آنلاین</a></li>
                               
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-12">
                    <div class="socail_links">
                        <ul>
                            <li><a href="https://www.instagram.com/smartbourse/?hl=en" class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s"> <i class="fa fa-instagram"></i> </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-right_text">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center wow fadeInUp" style="direction: rtl;" data-wow-duration="1s" data-wow-delay="1.3s"><script> </script> تمامی حق و حقوق این سایت محفوظ می باشد. توسط <a href="https://smartbourse.com" target="_blank">SmartBourse  2019 &copy;</a>

                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--/ footer end  -->

media/templates/partials/header.html
{% load static %}

<div class="header-main">
    <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
            <div class="container-fluid p-0">
                <div class="row align-items-center no-gutters">
                    <div class="col-xl-1 col-md-1 col-lg-1">
                        <div class="logo-img" style="padding: 40px 0 0 0">
                            <a href="">
                                <img src="{% static 'assets/img/header/LOGO.png' %}" alt="" />
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-9 col-md-9 col-lg-9">
                        <div class="main-menu  d-none d-lg-block text-center">
                            <nav>
                                <ul id="navigation">
                                    <li {% if view.page_name == 'خانه' %}class="say_hi"{% endif %}><a href="{% url 'pages:home' %}">خانه</a></li>
                                    <li {% if view.page_name == 'تکنوفاند' %}class="say_hi"{% endif %}><a href="{% url 'technofund:posts' %}">تکنوفاند </a></li>
                                    <li {% if view.page_name == 'آموزش' %}class="say_hi"{% endif %}><a href="{% url 'tutorial:posts' %}"> آموزش </a></li>
                                    <li {% if view.page_name == 'عرضه اولیه' %}class="say_hi"{% endif %}><a href="{% url 'market:primary-market' %}">عرضه اولیه</a></li>
                                    <li {% if view.page_name == 'آکادمی' %}class="say_hi"{% endif %}><a href="{% url 'shop:products' %}">آکادمی</a></li>
                                    <li {% if view.page_name == 'اخبار' %}class="say_hi"{% endif %}><a href="{% url 'news:posts' %}">اخبار</a></li>
                                    <li {% if view.page_name == 'تماس با ما' %}class="say_hi"{% endif %}><a href="{% url 'pages:contact' %}">تماس با ما</a></li>
                                    <li {% if view.page_name == 'درباره با ما' %}class="say_hi"{% endif %}><a href="{% url 'pages:about' %}">درباره با ما</a></li>
                                    <li {% if view.page_name == 'افتتاح حساب آنلاین' %}class="say_hi"{% endif %}><a href="{% url 'pages:open-account' %}">افتتاح حساب آنلاین</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2 d-none d-lg-block">
                        <div class="log_chat_area d-flex align-items-end">

                            <!-- <a href=""><i class="fa fa-shopping-basket"><i class="fa fa-circle"></i></i></a> -->
                            <div class="log_chat_area d-flex align-items-end" style="margin-right: 10px;">
                                <a href="#" data-scroll-nav="0">ورود / عضویت </a>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

media/templates/partials/slider.html
{% load static %}
<div class="body-inner">

    <!-- Revolution Slider -->
    <section id="slider">
        <div id="rev_slider_44_1_wrapper" class="rev_slider_wrapper fullscreen-container" data-alias="paintbrush-addon" data-source="gallery" style="background:transparent;padding:0px;">
            <!-- START REVOLUTION SLIDER 5.4.8.1 fullscreen mode -->
            <div id="rev_slider_44_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.4.8.1">
                <ul>
                    <!-- SLIDE  -->
                    <li data-index="rs-66" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="{% static 'assets/plugins/slider-revolution/assets/images/100x50_paintbrush_bg2.jpg' %}" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" data-revaddonpaintbrush='{"size":200,"origsize":200,"blurAmount":10,"fadetime":600,"image":"static/assets/plugins/slider-revolution/assets/images/paintbrush_bg2.jpg","edgefix":10,"fixedges":true,"style":"round","blur":true,"scaleblur":false,"responsive":false,"disappear":true,"carousel":false}' data-revaddonpaintbrushedges="1">
                        <!-- MAIN IMAGE -->
                        <img src="{% static 'assets/plugins/slider-revolution/assets/images/paintbrush_bg2.jpg' %}" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                        <!-- LAYERS -->
                        <!-- LAYER NR. 1 -->
                        <div class="tp-caption tp-shape tp-shapewrapper  tp-resizeme rs-parallaxlevel-2" id="slide-66-layer-11" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['375','295','295','245']" data-width="360" data-height="3" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"delay":300,"speed":2000,"frame":"0","from":"z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;fb:10px;","to":"o:1;rZ:-45;fb:0;","ease":"Back.easeInOut"},{"delay":"wait","speed":600,"frame":"999","to":"rZ:0deg;opacity:0;fb:10px;","ease":"Back.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;background-color:rgb(255,255,255);">
                            <div class="rs-looped rs-slideloop" data-easing="Linear.easeNone" data-speed="5" data-xs="0" data-xe="0" data-ys="-10" data-ye="10"> </div>
                        </div>
                        <!-- LAYER NR. 2 -->
                        <div class="tp-caption tp-shape tp-shapewrapper  tp-resizeme rs-parallaxlevel-1" id="slide-66-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['375','295','295','245']" data-width="360" data-height="3" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"delay":700,"speed":2000,"frame":"0","from":"z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;fb:10px;","to":"o:1;rZ:45;fb:0;","ease":"Back.easeInOut"},{"delay":"wait","speed":600,"frame":"999","to":"rZ:-45deg;opacity:0;fb:10px;","ease":"Back.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6;background-color:rgb(255,255,255);">
                            <div class="rs-looped rs-slideloop" data-easing="Linear.easeNone" data-speed="5" data-xs="0" data-xe="0" data-ys="10" data-ye="-10"> </div>
                        </div>
                        <!-- LAYER NR. 3 -->
                        <div class="tp-caption tp-resizeme rs-parallaxlevel-12" id="slide-66-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['310','230','240','208']" data-fontsize="['50','50','40','25']" data-lineheight="['60','60','50','35']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":500,"speed":1000,"frame":"0","from":"x:-150px;z:0;rX:0deg;rY:-45deg;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;fb:10px;","to":"o:1;fb:0;","ease":"Back.easeInOut"},{"delay":"wait","speed":600,"frame":"999","to":"x:150px;rY:45deg;opacity:0;fb:10px;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[5,5,5,2]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[10,10,10,10]" style="z-index: 7; right: 0px; white-space: nowrap; font-size: 50px; line-height: 60px; font-weight: 600; color: #ffffff; letter-spacing: 0px;font-family:Poppins;background-color:rgb(0,0,0);">
                            <div class="rs-looped rs-slideloop" data-easing="Linear.easeNone" data-speed="10" data-xs="-20" data-xe="20" data-ys="0" data-ye="0">Smart Bourse  <div class='frontcornertop'></div>
                                <div class='backcornertop'></div>
                            </div>
                        </div>
                        <!-- LAYER NR. 4 -->
                        <div class="tp-caption   tp-resizeme rs-parallaxlevel-10" id="slide-66-layer-9" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['378','298','298','248']" data-fontsize="['50','50','40','25']" data-lineheight="['60','60','50','35']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":900,"speed":1000,"frame":"0","from":"x:150px;z:0;rX:0deg;rY:45deg;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;fb:10px;","to":"o:1;fb:0;","ease":"Back.easeInOut"},{"delay":"wait","speed":600,"frame":"999","to":"x:-150px;rY:-45deg;opacity:0;fb:10px;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[5,5,5,2]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[10,10,10,10]" style="z-index: 8; white-space: nowrap; font-size: 50px; line-height: 60px; font-weight: 600; color: #ffffff; letter-spacing: 0px;font-family:Poppins;background-color:rgb(0,0,0);">
                            <div class="rs-looped rs-slideloop" data-easing="Linear.easeNone" data-speed="10" data-xs="20" data-xe="-20" data-ys="0" data-ye="0">BY ITS MYSTERIOUS LIFE <div class='frontcorner'></div>
                                <div class='backcorner'></div>
                            </div>
                        </div>
                        
                        
                    </li>
                   
                </ul>
                <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
            </div>
        </div><!-- END REVOLUTION SLIDER -->
        <script type="text/javascript">
            var revapi44,
                tpj;
            (function () {
                if (!/loaded|interactive|complete/.test(document.readyState)) document.addEventListener("DOMContentLoaded", onLoad);
                else onLoad();

                function onLoad() {
                    if (tpj === undefined) {
                        tpj = jQuery;
                        if ("off" == "on") tpj.noConflict();
                    }
                    if (tpj("#rev_slider_44_1").revolution == undefined) {
                        revslider_showDoubleJqueryError("#rev_slider_44_1");
                    } else {
                        revapi44 = tpj("#rev_slider_44_1").show().revolution({
                            sliderType: "standard",
                            jsFileLocation: "//localhost/revslider/public/assets/js/",
                            sliderLayout: "fullscreen",
                            dottedOverlay: "none",
                            delay: 9000,
                            navigation: {
                                keyboardNavigation: "off",
                                keyboard_direction: "horizontal",
                                mouseScrollNavigation: "off",
                                mouseScrollReverse: "default",
                                onHoverStop: "off",
                                
                            },
                            responsiveLevels: [1240, 1024, 778, 480],
                            visibilityLevels: [1240, 1024, 778, 480],
                            gridwidth: [1240, 1024, 778, 480],
                            gridheight: [868, 768, 960, 720],
                            lazyType: "none",
                            parallax: {
                                type: "3D",
                                origo: "slidercenter",
                                speed: 400,
                                speedbg: 0,
                                speedls: 0,
                                levels: [5, 10, 15, 20, 25, 30, 35, 40, -2, -4, -6, -8, -10, -12, -14, 55],
                                ddd_shadow: "off",
                                ddd_bgfreeze: "on",
                                ddd_overflow: "hidden",
                                ddd_layer_overflow: "hidden",
                                ddd_z_correction: 150,
                                disable_onmobile: "on"
                            },
                            spinner: "off",
                            stopLoop: "on",
                            stopAfterLoops: 0,
                            stopAtSlide: 1,
                            shuffle: "off",
                            autoHeight: "off",
                            fullScreenAutoWidth: "off",
                            fullScreenAlignForce: "off",
                            fullScreenOffsetContainer: "",
                            fullScreenOffset: "",
                            disableProgressBar: "on",
                            hideThumbsOnMobile: "off",
                            hideSliderAtLimit: 0,
                            hideCaptionAtLimit: 0,
                            hideAllCaptionAtLilmit: 0,
                            debugMode: false,
                            fallbacks: {
                                simplifyAll: "off",
                                nextSlideOnWindowFocus: "off",
                                disableFocusListener: false,
                            }
                        });
                    }; /* END OF revapi call */
                    RevSliderPaintBrush(tpj, revapi44);
                    if (typeof ExplodingLayersAddOn !== "undefined") ExplodingLayersAddOn(tpj, revapi44);
                }; /* END OF ON LOAD FUNCTION */
            }()); /* END OF WRAPPING FUNCTION */
        </script>
    </section>
    <!-- end: Revolution Slider-->
</div>